// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnwgSxP1gt5fkIfgEnYm-bivl03Ss8cFM',
    appId: '1:1034598304627:web:f16646c63ca7801a065306',
    messagingSenderId: '1034598304627',
    projectId: 'exam-fb81b',
    authDomain: 'exam-fb81b.firebaseapp.com',
    storageBucket: 'exam-fb81b.appspot.com',
    measurementId: 'G-J9QYT61BEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwq0Il4NRn-sr-fBUOC5XVuHqsDcaEEF0',
    appId: '1:1034598304627:android:1fe90753349bfdc3065306',
    messagingSenderId: '1034598304627',
    projectId: 'exam-fb81b',
    storageBucket: 'exam-fb81b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMBLrD3BfcTHBtUdOMV-3Ybyqdd9gQwgA',
    appId: '1:1034598304627:ios:da053cc60831b915065306',
    messagingSenderId: '1034598304627',
    projectId: 'exam-fb81b',
    storageBucket: 'exam-fb81b.appspot.com',
    iosClientId: '1034598304627-c9alr5omc7a6vet55pvv33pgh7rln0a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.logi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMBLrD3BfcTHBtUdOMV-3Ybyqdd9gQwgA',
    appId: '1:1034598304627:ios:da053cc60831b915065306',
    messagingSenderId: '1034598304627',
    projectId: 'exam-fb81b',
    storageBucket: 'exam-fb81b.appspot.com',
    iosClientId: '1034598304627-c9alr5omc7a6vet55pvv33pgh7rln0a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.logi',
  );
}
